name: publish my image to docker hub

on: 
  push:
    master:

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
     -  name: checkout
        uses: actions/checkout@v3
     -  name: build
        run: |
           docker build . -t mutiuadeniyi290/hello-docker:latest
     -  name: publish
        run: |
          docker login -u mutiuadeniyi290 -p ${{ secrets.DOCKER_HUB_TOKEN}}   
          docker push mutiuadeniyi290/hello-docker:latest